---
version: "2.1"
services:
    minetest:
        image: lscr.io/linuxserver/minetest:latest
        container_name: minetest
        env_file: /root/.env
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Etc/UTC
            - "CLI_ARGS=--gameid minetest --port 30000" #optional
        volumes:
            - /root/minetest-data:/config/.minetest
        ports:
            - 30000:30000/udp
        restart: unless-stopped
